[tool.poetry]
name = "quizcard"
version = "0.1.0"
description = ""
authors = ["Aidar Rakhimov <a.rakhimov@cian.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
gspread = "^5.12.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
